export const AUTO_BRANDS = [
  { value: 'Alfa Romeo', label: 'Alfa Romeo' },
  { value: 'Audi', label: 'Audi' },
  { value: 'BMW', label: 'BMW' },
  { value: 'Chevrolet', label: 'Chevrolet' },
  { value: 'Citroën', label: 'Citroën' },
  { value: 'Dodge', label: 'Dodge' },
  { value: 'Fiat', label: 'Fiat' },
  { value: 'Ford', label: 'Ford' },
  { value: 'Geely', label: 'Geely' },
  { value: 'Honda', label: 'Honda' },
  { value: 'Hyundai', label: 'Hyundai' },
  { value: 'Jaguar', label: 'Jaguar' },
  { value: 'Jeep', label: 'Jeep' },
  { value: 'Kia', label: 'Kia' },
  { value: 'LADA', label: 'LADA' },
  { value: 'Land Rover', label: 'Land Rover' },
  { value: 'Lexus', label: 'Lexus' },
  { value: 'Mazda', label: 'Mazda' },
  { value: 'Mercedes-Benz', label: 'Mercedes-Benz' },
  { value: 'Mitsubishi', label: 'Mitsubishi' },
  { value: 'Nissan', label: 'Nissan' },
  { value: 'Opel', label: 'Opel' },
  { value: 'Peugeot', label: 'Peugeot' },
  { value: 'Porsche', label: 'Porsche' },
  { value: 'Renault', label: 'Renault' },
  { value: 'Skoda', label: 'Skoda' },
  { value: 'Subaru', label: 'Subaru' },
  { value: 'Suzuki', label: 'Suzuki' },
  { value: 'Tesla', label: 'Tesla' },
  { value: 'Toyota', label: 'Toyota' },
  { value: 'Volkswagen', label: 'Volkswagen' },
  { value: 'Volvo', label: 'Volvo' },
  { value: 'Другой', label: 'Другой' },
];
